### ISSUE TITLE
maddy 0.8 something broke email_localpart_optional

### ISSUE THREAD

**Issue by petrm** [foxcpp/maddy#751]
# Describe the bug

I have maddy set up as described here: https://maddy.email/multiple-domains/.

```
    check {                   
        authorize_sender {
            user_to_email chain {  
            step email_localpart_optional           # remove domain from username if present
            step email_with_domain $(local_domains) # expand username with all allowed domains
            }                                        
        }                                                         
    } 
```
Something has changed in 0.8, because when I authenticate with `user@email.tld`, I get the error below.

```
maddy  | 2025-01-25T19:31:05.563762356Z submission/sasl: authentication failed  {"reason":"no auth. provider accepted creds, last err: unknown credentials","src_ip":"192.168.1.2:59842","username":"printer@domain.tld"}
```

Authenticating with just `user` allows the client to log in, but then I end up with:
```
maddy  | 2025-01-25T19:38:41.643632364Z submission/sasl: authentication failed  {"reason":"no auth. provider accepted creds, last err: unknown credentials","src_ip":"192.168.1.2:39680","username":"printer@domain.tld"}
```

For now I rolled back to 0.7.1.

# Configuration file

Nothing was changed in the config.

* maddy version: 0.8

**Comment by foxcpp** [comment]
c48332a should fix the issue

**Comment by petrm** [comment]
I built master c852199ec9447d2fcfc58dd9cd35e68a0df1627f and the problem is still there. Any debugging I can do?

**Comment by foxcpp** [comment]
Try again with ef7fa21

**Comment by foxcpp** [comment]
Try again with [01c65cf](https://github.com/foxcpp/maddy/commit/01c65cfb0e40d3c5898ce831fc45a24f0f261ab9)

**Comment by petrm** [comment]
Tested, [01c65cf](https://github.com/foxcpp/maddy/commit/01c65cfb0e40d3c5898ce831fc45a24f0f261ab9) works fine.
